# Generated by Django 5.0.9 on 2025-02-17 10:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dzuro3ezl/image/upload/v1739786072/lifepage/user/njp6vfunnf1as8g4fcqp.png', max_length=255, verbose_name='image'),
        ),
    ]
