# Generated by Django 5.0.9 on 2025-01-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_name_alter_profile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='upload/user/images/avatar.jpg', upload_to='upload/user/images/'),
        ),
    ]
