# Generated by Django 5.0.9 on 2025-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='commentCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='likepost',
            name='likeCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
