# Generated by Django 5.0.9 on 2025-01-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_commentpost_commentcount_likepost_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='commentCount',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='likeCount',
        ),
        migrations.AddField(
            model_name='post',
            name='no_of_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
